version: '3'

services:
  app:
    container_name: endpoint-challenge
    image: endpoint-challenge:0.0.1-SNAPSHOT
    build: ./
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"
volumes:
  database-data:
