name: contrast-scan-action

on:
  push:
    branches:
      - "master"

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Maven
        run: |
          curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
          apt-get update
          apt-get -y install unzip
          unzip -d /usr/share maven.zip
          rm maven.zip
          ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
          echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build jar
        run: |
          mvn clean install -DskipTests

      - name: Contrast Scan Action
        uses: Contrast-Security-OSS/contrastscan-action@PROD-1800-rewrite-gh-action-with-cli
        with:
          artifact: target/demo-0.0.1-SNAPSHOT.jar
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORG_ID }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          projectName: endpoint-challenge

      - name: verify sarif contents
        run: |
          cat results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
