name: SCA DotNet

on:
  push:
    branches:
      - "master"

jobs:
  perform-sca-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dotnet app
        uses: actions/checkout@v3
        with:
          repository: Azure-Samples/dotnet_core_sample

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: dotnet build and publish
        run: |
          dotnet build --configuration Release
          dotnet publish -c Release -o myapp 

      - name: Contrast SCA Action
        uses: Markkuu/contrast-sca-action-test@main
        with:
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          filePath: .
