name: SCA Python

on:
  push:
    branches:
      - "master"

jobs:
  perform-sca-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gradle app
        uses: actions/checkout@v3
        with:
          repository: swinton/github-app-demo.py

      - name: Contrast SCA Action
        uses: Markkuu/contrast-sca-action-test@main
        with:
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          filePath: .
